name: nix-info
version: '0.1.0.0'
synopsis: brew info clone for Nix
description: See README at <https://github.com/nix-hackers/nix-info#readme>
category: Development
stability: experimental
homepage: https://github.com/nix-hackers/nix-info
github: nix-hackers/nix-info
author: Eric Bailey
maintainer: eric@ericb.me
license: BSD3
extra-source-files:
- ChangeLog.md

ghc-options: -Wall

dependencies:
- base >=4.9 && <4.10
- aeson >=1.0 && <1.2
- string-conversions >=0.4 && <0.5
- text >=1.2 && <1.3
- turtle >=1.3 && <1.4
- unordered-containers >=0.2 && <0.3
- url >=2.1 && <2.2

library:
  source-dirs: src
  exposed-modules:
  - NixInfo
  - NixInfo.Types

executables:
  nix-info:
    main: Main.hs
    source-dirs: app
    dependencies:
    - nix-info
